
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sccp
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#多数据源配置
spring:
  datasource:
    dynamic:
#      配置默认数据源
      primary: master
#      开启严格模式
      strict: true
      datasource:
#        默认数据源
        master:
          url: jdbc:mysql://localhost:3306/sccp
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
#          从数据源
        slave:
          url: jdbc:mysql://localhost:3306/sccp2
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456

#配置服务端口
server:
  port: 8080


#mybatis-plus配置
mybatis-plus:
  configuration:
#    日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapper xml文件配置
  mapper-locations: classpath:/mapper/*.xml

